### ISSUE TITLE
Parsing Wikidata entities missing a "type" tag.

### ISSUE THREAD

**Issue by shilad** [Wikidata/Wikidata-Toolkit#105]
Greetings, I'm trying to replace my custom Wikidata parsing code with WikidataToolkit. I'm using the following bit of code to parse the JSON associated with entities:

```java
if (MwRevision.MODEL_WIKIBASE_ITEM.equals(mwRevision.getModel())) {
    mwDoc = mapper.readValue(mwRevision.getText(), JacksonItemDocument.class);
} else if (MwRevision.MODEL_WIKIBASE_PROPERTY.equals(mwRevision.getModel())) {
    mwDoc = mapper.readValue(mwRevision.getText(), JacksonPropertyDocument.class);
}
```

The problem I'm encountering is that some entities in the XML dump are missing a "type" attribute. For example, the JSON for Q25 (Jack Bauer) in http://dumps.wikimedia.org/wikidatawiki/20141009/wikidatawiki-20141009-pages-articles.xml.bz2 starts with the following and never has a type attribute.

```json
{"label":{"en":"Jack Bauer",
```
Is this a known problem? If so, is there a workaround? Since I'm jumping into WikidataToolkit at a relatively low level, I wonder if some of the higher level code I'm not using is working around this in some way.

Thanks for the excellent tool!

**Comment by mkroetzsch** [comment]
Our general workaround for such issues is to try and ignore the broken data. We do not attempt to recover the entity data in such cases, but we try to move on to get the remaining entities. This should generally work in the XML (since the JSON parsing is only invoked on individual entity serializations), and since the merge of #111 is should also work on JSON dumps (since we have a more robust recovery strategy for those now). XML dumps have been more buggy for a while, and it turned out that JSON dumps are also faster to process, so this is our default choice now. You need XML, of course, if you want to know about revisions and editors; JSON has only the data without any metdata.

So far, errors in the JSON have been fairly random, and most of them were fixed in future dumps. Therefore, I don't think it makes much sense to write code that tries to recover such data -- we would end up with a lot of heuristics in our code that are hopefully not needed once Wikibase fixes the underlying error. 

I am closing this bug for now. Feel free to reopen if you think that the missing type issue is a more persistent problem that we should address with special code.
