### ISSUE TITLE
How to use Wikidata-Toolkit with proxy servers?

### ISSUE THREAD

**Issue by GlorimarCastro** [Wikidata/Wikidata-Toolkit#145]
Where can I specify a proxy server for the connection? If there is not way, it would be nice to be able to do that.

**Comment by mkroetzsch** [comment]
There is currently no such options. We are just using regular Java functions to access the Web. I am sure there are ways to configure them to use proxies, but I don't know yet. In order to ensure testability of our code, we perform all web access through a single helper class. This means that there is a single point where one could (hopefully) make such proxy settings to affect all of our code in all modules.

If you have any hints on how to best set proxies in Java, feel free to post them here. The class I mentioned is WebResouceFetcherImpl, so you could also try to make the required changes there directly for solving your problem for now. It's not that much code overall.

**Comment by GlorimarCastro** [comment]
I made some changes and I was able to connect using proxy settings. What I did was to create a method in WebResouceFetcherImpl to set the proxy, using the Proxy class from java.net, for the URLConnection. Also, I created the same method in WmfDumpFileManager, since in this class is where the method findDumpsOnline() is. So, if a person is using a proxy server the only thing he or she have to do is set the proxy to any WmfDumpFileManager object that is using. And if a proxy were set, the findDumpsOnline method is going to set the same proxy to the URLConnection in WebResouceFetcherImpl.

I apologize for any grammatical error. English is not my first language.

**Comment by mkroetzsch** [comment]
Sounds good. I think we would fist introduce a static (global) default configuration for the proxy server. Otherwise we would need to have methods like the one you mention for WmfDumpFileManager in many other places as well (e.g., in the API components and in the RDF export components). If non-static configurations should be needed, this could always be added later.

Is your code somewhere on github so we can borrow from it?

Your English is fine (but then I am not a native speaker either ;-).

**Comment by GlorimarCastro** [comment]
I think that a static configuration would be perfect. I do not have my code in github, but I could put it in, so all of you can borrow it. At the same time I created another example of how to extract all the entities that are "instance of" some class (property) in Wikidata. That would maybe interest someone. So when I have the code in github I am going to post the git link.

**Comment by GlorimarCastro** [comment]
The wikidata-toolkit with changes made by me can be found in the next github link:
https://github.com/GlorimarCastro/glorimar-wikidata-toolkit

If anyone is interested, the next link is to a repository where you can find different applications I'm creating for data extraction using local wikidata dumps:
https://github.com/GlorimarCastro/wikidata-toolkit-ll

**Comment by GlorimarCastro** [comment]
Right now I am not using the proxy server setting, because I used them just to download the dumps. Once I downloaded the dumps I disabled them, but the code is still there.
