### ISSUE TITLE
Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token

### ISSUE THREAD

**Issue by notconfusing** [Wikidata/Wikidata-Toolkit#160]
Just today I started getting this error on every Wikidata Item I try and process.

```
ERROR - Error when reading JSON for entity: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
```

**Comment by mkroetzsch** [comment]
Yes, this is a known problem with the JSON dumps. Wikidata folks are working on it. See https://lists.wikimedia.org/pipermail/wikidata/2015-August/006808.html for updates. I will close this here, since there is nothing we can do. The only workaround now is to use older JSON dumps instead of the most recent ones.

**Comment by notconfusing** [comment]
Thanks. I saw the discussion on Wikidata list right after I posted this
bug. Just have to wait....
