### ISSUE TITLE
Wikibase API: Support wbeditentity

### ISSUE THREAD

**Issue by zazi** [Wikidata/Wikidata-Toolkit#162]
I'm trying to utilise the datamodel package from the Wikidata-Toolkit to create Entities (Items and Properties) that I would like to add to a Wikibase instance via the MediaWiki HTTP API (https://github.com/zazi/wikidata-d-swarm-importer/tree/own_mediawiki_api_client). However, it looks like that the Datamodel builder (org.wikidata.wdtk.datamodel.helpers.Datamodel) is optimized for read-only processing (where all parts of an Entity are somehow available). When I would like to create a new Entity (Item or Property), then I expect that the system mints new identifier for them. By utilising the builder methods of Datamodel builder, e.g., Datamodel#makeItemDocument, every property needs to be non-null. For the majority of parameter this isn't a problem, however, the id value should be null, because I expect that system will create an identifier for a new item at server side.
Any chance to prepare the Datamodel builder for creating entities for writing as well? - i.e., where only fields are mandatory that need to be mandatory for minimal writing/entity creation.

PS: I can also have a look at the code and try to fix this issue at my own

**Comment by zazi** [comment]
I guess I should switch to the POJOs in org.wikidata.wdtk.datamodel.json.jackson instead of utilising the "original/real" data model. Why the differentiation?

**Comment by mkroetzsch** [comment]
Hi Zazi. Now we already have two questions. A relevant answer to both is that we are about to implement API writing support in WDTK. The issues you raise are very relevant; at the same time, we have not yet planned how exactly these things will work. There will be an interface in WDTK that allows data to be written or edited. This interface will accept arbitrary datamodel objects, so it won't matter there if you use the Jackson implementation or the vanilla POJOs. It will convert internally as needed (in other words, if you generate Jackson-based objects right away, this will safe some time; but for an application that does online operations, this time won't matter much).

Regarding the second question, the reason why we have both is that the Jackson implementation has more complicated data structures to support serialisation/deserialisation. Jackson objects therefore need more memory. Maybe WDTK will at some point switch to using Jackson as the default for the Datamodel helper methods.

Now to the first question. The question is which API methods require which type of input. Looking at wbeditentity, it seems to me that the "data" parameter is not relevant for defining the ID of the entity. The parameters "id" and "new" are used to control what should happen. If it does not matter if "data" contains any entity or not, then one could also just use some entity object instead of null (e.g., we could provide a final static entity object for this purpose).

On the other hand, we have to support statements (called "claims" in the API docs) that have no id, in order to create new statements. On the other hand, for removing claims, we probably want to provide a dedicated function rather than trying to tweak the Jackson objects to produce some serialized version with the "remove" data in it. Therferefore, we should have two kinds of methods at least: one for removing claims from an entity document (it would take a list of statement ids and some specification of which entity to delete); another for setting/adding data to an existing or new entity (it would take an EntityDocument object, possibly with "new" statements, and some way of identifying the entity or saying that a new entity should be created).

Maybe @guenthermi has other comments. He is looking into the methods for addressing the write API now.



Instead of using "null", one could also use another kind of "local" ids that are then ignored

**Comment by zazi** [comment]
@mkroetzsch thanks a lot for your fast reply. Right now I'm trying to modify things in datamodel package as needed to get the right serialisation out of the POJOs.

1. I disabled some ID=null checks
2. I'm trying to added "original/real" data model class converting to Jackson classes for ItemDocument and PropertyDocument

Currently, I would like to create new properties (with no statements attached) and new items with statements/claims attached (i.e. I would like to make use of the "wbeditentity" action at the Wikibase HTTP API). Let's see how far I'll get ;)

**Comment by zazi** [comment]
I'm pushing my modification to https://github.com/zazi/Wikidata-Toolkit/commits/wikibase_api_write_modifications right now.

**Comment by mkroetzsch** [comment]
Ok, good luck. Comments on your earlier points:

1. I still wonder why you actually need to serialise the data in JSON without the id. Does the wikibase API care about this at all?

2. You can create Jackson objects directly using the JacksonObjectFactory. If you want to convert from one datamodel implementation to another, you can use DatamodelConverter for this purpose.

In addition, you might want to look at the work we are now doing in #157. It already includes code for authenticating with a user login to the Wikibase API. You will probably need this too.

**Comment by zazi** [comment]
@mkroetzsch Thanks a lot (again) for the useful hints re. data converting (I should had a closer look at DatamodelConverter before ... :\). I'll try running DatamodelConverter with JacksonObjectFactory. Re. authentication, I followed the example at https://www.mediawiki.org/wiki/API:Edit/Editing_with_Python (see https://github.com/zazi/wikidata-d-swarm-importer/blob/own_mediawiki_api_client/src/main/java/org/dswarm/wikidataimporter/WikibaseAPIClient.java#L137). I'm not 100% sure, whether this really works as expected (since I'm still struggling with serializing the JSON). However, the requests work at least, so that I'm getting to the real edit requests.

**Comment by zazi** [comment]
Ok, so far I was able to create a new Property at our local Wikibase instance (at least; with the code from my importer), i.e., the authentication code is working. I'm doing the POJO converting with my own converters right now (see https://github.com/zazi/Wikidata-Toolkit/commits/wikibase_api_write_modifications). I'll test DatamodelConverter + JacksonObjectFactory in the future. Re. whether a new entity should have an id or not - from the API documentation (https://www.wikidata.org/w/api.php?action=help&recursivesubmodules=1#wbeditentity) it says "new: If set, a new entity will be created. Set this to the type of the entity you want to create - currently 'item'|'property'. It is not allowed to have this set when 'id' is also set.". So I think I can't mint my own entity identifier at Wikibase, or?

**Comment by mkroetzsch** [comment]
Regarding the API documentation: this text only refers to the values of the parameters "new" and "id". Your reading seems to be correct there. This is unrelated to your original question though. The "id" of an EntityDocument (that you want to set to null) will show up in the JSON serialisation, which you want to pass to the "data" parameter of the API. This is not related to the parameters "id" and "new" that the documentation refers to. I don't know if the JSON in "data" will tolerate (ignore) id information given there in general.

Regarding your overall task: if you plan to do one-time importing, a better way is to generate an XML dump file that you can import. It will be much faster to import and it allows you to set the id if you like. To do this, you would have to wrap the JSON we generate into the XML data structures as used in the Wikidata dump files, escaping characters as needed. We don't have code for this, but it should be rather easy to do (compared to using the API).

**Comment by zazi** [comment]
@mkroetzsch: at the end we would like to do both - inserting small and big chunks. Ideally, we would like to do all this at running instance, i.e., no batch import with an offline system. Everything would be fine, if the XML dump import (https://www.mediawiki.org/wiki/Manual:Importing_XML_dumps ?) support this feature. Re. import data via wbeditentity, I still have an issue at server-side, which I cannot fully interpret right now. I'll post this at the wikidata-tech mailing list (or somewhere else (appropriated)).

Re. entity id minting. From my current reading and understanding, prefixes for Item ("Q") and Property ("P") are fix and are heavily utilised in the code. I'm not sure how the nature of entity id minting is designed in Wikibase (maybe you have some pointers for further reading on this topic). However, I guess that this should be done on server-side (to guarantee certain integrity constraints etc.).

Thanks a lot again for your insightful comments and remarks.

**Comment by mkroetzsch** [comment]
Writing through the API is now widely supported (#165). See the new example program for details.

**Comment by zazi** [comment]
coolo, thx. looking forward to test it ;)
