### ISSUE TITLE
Basic tuple storage implementation

### ISSUE THREAD

**Issue by mkroetzsch** [Wikidata/Wikidata-Toolkit#18]
A basic implementation for managing a list of n-tuples (one might say: a table, but maybe with additional constraints) in memory should be provided. The implementation should support basic (non-compound) queries and iteration operations. This functionality should be defined in an interface.

**Comment by robertvazan** [comment]
@Tpt @wetneb This issue is quite old. Is this (and related #19 and #20) still considered for inclusion in WDTK? AFAIK there are dedicated SPARQL engines with their own storage. Wikidata is certainly using one. Embedded WDTK implementation would be easier to use in some cases, but would it be good enough to be useful? Wikidata dump is ~100GB by now.

**Comment by wetneb** [comment]
I cannot really make sense of this, it's not clear to me what this was for.  I would say that implementing a SPARQL engine is clearly out of scope of WDTK. Let's close this then.
