### ISSUE TITLE
Adds a clean support of redirections

### ISSUE THREAD

**Issue by Tpt** [Wikidata/Wikidata-Toolkit#262]
WikidataToolkit should provide a clean support of redirections. It would allow to avoid bad hacks like #241

**Comment by wetneb** [comment]
Marking this as a good first issue with the understanding that this means:
* adding a class to represent a redirected entity;
* making sure this class can be parsed from its JSON representation as stored in the dumps;
* adapting the code changes in #241 to use this instead.

Then, it might be interesting to expose redirects to dump readers (instead of ignoring them). We should make sure this does not silently break existing code.

**Comment by snehasi** [comment]
Hi @wetneb,

Is this issue still open? I'm interested in working on it.

@kanikasaini, @Tanish-Gupta and I are working as a team. We are looking for some other good first issues to work on. It would be wonderful if you could please direct us to other such issues we can work on, which are not labelled as good first issue but could be great for starters.

Thank you!

**Comment by wetneb** [comment]
Yes this is still open and I still think that is a great first issue!

Thank you for your contributions so far by the way! May I ask if you are doing this within the scope of a particular program or course, perhaps?

**Comment by snehasi** [comment]
Hi @wetneb,

Yes, we're doing this within the scope of a university course!
I've added the classes and made modifications to related files, could you please take a look?

Thank you!

**Comment by Tpt** [comment]
Hi! Sorry for not being fast enough to reply on this issue.

There is already a class for redirection. It is called `EntityRedirectDocument`. So, no change is needed to add a new class for it. However it might be nice to make the `EntityDocumentProcessor` interface able to get `EntityRedirectDocument` and make `WikibaseRevisionProcessor` deserialize the redirections.
