### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#268]
Hi,

First, this library looks fantastic! So much cleaner than the ones we have in Python. Thank you for that!

Any chances logging in with OAuth could be supported? That would be massively useful. As far as I can tell ApiConnection only works with standard credentials for now.

Keep up the good work!

**Comment by Tpt** [comment]
> First, this library looks fantastic! So much cleaner than the ones we have in Python. Thank you for that!

Thank you!

> Any chances logging in with OAuth could be supported?

We should definitely support OAuth. Feel free to write a pull request.

**Comment by wetneb** [comment]
@Tpt great! Not sure my Java is fluent enough to deserve to be included in that library, and pretty sure it would be very unreasonable to procrastinate my PhD on that, but I'll definitely consider it!

**Comment by lucaswerkmeister** [comment]
scribejava/scribejava#852 adds a class describing MediaWiki’s OAuth URLs to the ScribeJava API. Since it might be a while until that pull request is merged and the next version of the library is released, I hereby as the original and sole author of the [`MediaWikiApi` class](https://github.com/lucaswerkmeister/scribejava/blob/mediawiki/scribejava-apis/src/main/java/com/github/scribejava/apis/MediaWikiApi.java) grant you permission to copy that class into Wikidata Toolkit (ideally with a different package name) and start using it right now :)

(Note: the pull request also adds a `MediaWikiExample` class, but since that is mostly derived from other examples in the repository, I cannot grant you a license for that.)

**Comment by lucaswerkmeister** [comment]
If I was allowed to make breaking changes, I think I would implement it a bit like this (sublists indicate subclasses):

- `ApiConnection`: abstract class with one abstract method (`sendJsonRequest`) and a few static utility methods (`implodeObjects`, and perhaps the two current wikidata/testwikidata getters?)
  - `BasicApiConnection`: most of the current `ApiConnection` code – implements `sendJsonRequest` and manages cookies, but doesn’t do login (can be used for anonymous requests)
    - `UsernamePasswordApiConnection`: adds login/logout to `BasicApiConnection` by sending API requests which populate `BasicApiConnection`’s cookie store (the rest of the current `ApiConnection` code)
  - `OAuthApiConnection` – has methods for the three-legged OAuth flow using ScribeJava, and hopefully using some nice HTTP library (ScribeJava seems to come with something by default?) so we don’t need to bother with cookies etc. ourselves

What’s the policy on breaking changes in this project? (I guess if we keep the two current getters on `ApiConnection`, this should in practice be backwards compatible for most users who don’t use the `ApiConnection` constructor directly.)

**Comment by wetneb** [comment]
@lucaswerkmeister I agree that this is the final state to aim at. I'll make a PR that starts the transition towards that, keeping `ApiConnection` concrete for now (but deprecating its constructors to indicate that people should migrate to `BasicApiConnection`.

**Comment by afkbrb** [comment]
Closed since #411 is merged.
