### ISSUE TITLE
WikibaseDataFetcher getEntityDocument error "Unexpected character '<' "when using 0.7.0 

### ISSUE THREAD

**Issue by assafko** [Wikidata/Wikidata-Toolkit#293]
[WbGetEntitiesAction] - <Could not retrive data: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

can anyone assist? did data model change ? i am getting this error with all ids

**Comment by Tpt** [comment]
It seems that you received from Wikimedia servers a response that is not in JSON, probably an error page. Could you retry to see if you get this error again?

**Comment by assafko** [comment]
issue recreated over and over with different ids. i could not get more info.
had to upgrade to 0.8-SNAPSHOT which i built locally

**Comment by jacobrobertson** [comment]
Even this simple example will cause this error for me.
		ApiConnection con = ApiConnection.getWikidataApiConnection();
		String user = "x";
		String pass = "y";
		con.login(user, pass);
I attached the sources, and did a debug, and the reason was because wikidata was returning an HTML page to ApiConnection.getLoginToken.  I'm kind of stuck at this point, wondering if something changed with the way wikidata is interacting with the API?

**Comment by jacobrobertson** [comment]
When I run under 0.8.0-SNAPSHOT, I get this in the logs
[14:30:31,108]API warning [main]: Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.
[14:30:31,109]API warning [login]: Fetching a token via "action=login" is deprecated. Use "action=query&meta=tokens&type=login" instead.

**Comment by Tpt** [comment]
> I'm kind of stuck at this point, wondering if something changed with the way wikidata is interacting with the API?

The API URI used in v0.7 (https://www.wikidata.org/w/api.php/) is now returning a 404 error instead of working (I don't know why WikidataToolkit was using it at the first place). It is fixed in master.

> [14:30:31,109]API warning [login]: Fetching a token via "action=login" is deprecated. Use "action=query&meta=tokens&type=login" instead.

Thank you for the warning. I've just written a pull request with a change that removes this warning

**Comment by Tpt** [comment]
I just released version 0.8.0. This problem should be fixed in the new release.
