### ISSUE TITLE
Editing continues as an IP if the auth cookies expire

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#409]
If we login with WDTK and then the cookies expire (for instance because we logout from the same account with a browser), then editing in WDTK will continue as an IP, which is not desirable.

The `assert=` parameter can be used to make sure the action fails if we are not authenticated as the given user. We should use that:
https://www.mediawiki.org/wiki/API:Assert

**Comment by afkbrb** [comment]
Hi @wetneb, the abuse filter https://www.wikidata.org/wiki/Special:AbuseFilter/119  of Wikidata has the  notes:

> Blocks IP edits from OpenRefine, which are due to this bug:
https://github.com/Wikidata/Wikidata-Toolkit/issues/409
-- Pintoch, 2018-05-01
 Try to fix regex
− Pintoch 2018-05-02
Updated use of deprecated variables - Dannys712, 18 April 2020


Can that filter be removed now?

As Thad asked at https://groups.google.com/g/openrefine/c/sUCHI2gOn7M, I tried adapting the code of OpenRefine to support anonymous edits, but found that the edits were swallowed by this filter.

**Comment by thadguidry** [comment]
I think that...
1. Wikidata itself - already allows editing anonymously (no login required, but tracks your IP on edits).
2. Wikibases running at institutions - they might have networking already setup so that only teams with VPN access or setup with Zero Trust (Cloudflare, certs for example) would be able to access without authenticating to Wikibase instances because they are already considered part of the same network as the Wikibase instances and so are allowed to do edits anonymously.

For 1. folks who use OpenRefine for editing Wikidata will need to login (this seems to be some policy with Wikidata for registering accounts for Bots and other mass editing tools like OpenRefine, and so a login will probably always be required?)
For 2. However, its likely that there might be some folks at institutions that want anonymous edits supported from OpenRefine.  But no replies yet on the mailing list about that consensus.

**Comment by wetneb** [comment]
@afkbrb batches of edits made as an IP in Wikidata are not desirable:
* batch imports should only be done by users who have edited Wikidata manually first, to make sure they understand the datamodel correctly (e.g. difference between qualifier and reference)
* it should be easy to contact the person responsible for a batch import, so that any issues with the batch can be discussed;
* anonymous edits go into a patrolling queue which is reviewed manually by volunteers. Flooding this queue with automated edits puts unnecessary strain on these volunteers.

It is not clear to me why anonymous edits would be needed for custom Wikibases. In general, third-party wikis tend to be more conservative (disable anonymous edits altogether) because they have less reviewing capacity than large communities like Wikidata.

So I would not spend time adding such a feature.
