### ISSUE TITLE
Code duplication: determine an entity type by looking at the format of its id

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#424]
There are at least two places in our code where we try to guess the type of an entity based on the format of its id:

https://github.com/Wikidata/Wikidata-Toolkit/blob/ac2692ac35e3ae7fc8148f416322e1e6f07beca0/wdtk-datamodel/src/main/java/org/wikidata/wdtk/datamodel/implementation/EntityIdValueImpl.java#L134-L162

and

https://github.com/Wikidata/Wikidata-Toolkit/blob/d76e8ee421856f7aba6bff6cf1f8ab13e03f451d/wdtk-rdf/src/main/java/org/wikidata/wdtk/rdf/PropertyRegister.java#L199-L229

That is a problem: it is easy to forget to update one of them (it caused #407).
We should expose this functionality publicly in the `wdtk-datamodel` module. This raises questions:
* where should this static method live?
* what representation of the entity types should it return? Currently one uses the JSON strings, the other uses IRIs for datatypes. I think it should be IRIs for entity types since that is what the `EntityIdValue` interface offers… But then we probably need other static methods to help convert between all these formats? It's a bit of a mess :-/

**Comment by Tpt** [comment]
Yes, indeed it's a bit of a mess. The choice have been done at the beggining of WikidataToolkit to create URIs for each Wikibase datamodel enumeration (datatypes, entity types...), leading to this duplication. We have two options here:

1. Drop everywhere the URIs and only returns the JSON string ids that are used by Wikibase. It has the strong advantage of not having to update the mappings each time a new value is introduced.
2. Keep the library working as it is.

I would slightly prefer 2. because it is less disruptive for the library user. In this case we should probably have a method that returns the Datatype IRI. This method could be public in the `EntityIdValue` interface. We could then have package private conversion methods between the two representation in EntityIdValueImpl, just like it is done in `DatatypeIdImpl` for the datatype ids.

**Comment by wetneb** [comment]
Option 2 is fine with me too.
Since the entity type IRIs are also exposed publicly in `DatatypeIdValue` I would say that it would be good to have a public conversion utility, transforming `http://wikiba.se/ontology#WikibaseForm` (datatype IRI) to `http://www.wikidata.org/ontology#Form` (entity type IRI) and back. Conversion to JSON strings can stay private since they are not exposed except in the pathological case of unsupported entities.

**Comment by snehasi** [comment]
Hi

Is this issue still open? I was planning to work on it. Would appreciate if you could provide some pointers on it.

From first look, it seems that creating a function `entityIdToType` in some common module should suffice. 

Then we can replace the switch cases in `guessEntityTypeFromId` and `setPropertyTypeFromEntityIdValue` with a function call to `entityIdToType`.

The above mentioned function could have a flag to indicate whether JSON string should be returned, and we could default to IRIs or other way round. This way we might not even need to add a public function for transforming between JSON string and IRIs since we are preserving the old functions and just abstracting out the conversion logic to a common function. 

What are your thoughts about it?

**Comment by Tpt** [comment]
Hi! Yes, the issue is still open. Thank you for being interested in it!

For me `entityIdToType` (or `guessEntityTypeFromId`?) should return a `DatatypeIdValue` to be completely generic. And then, `EntityIdValueImpl.guessEntityTypeFromId` would just need to convert these types to the JSON IDs with a simple switch. We probably do not want to publicly present a method that returns JSON serialization internals.

**Comment by snehasi** [comment]
HI @Tpt,

`guessEntityTypeFromId` sounds like a better name for the function.

Although, if we return `DatatypeIdValue` and do conversions in `EntityIdValueImpl.guessEntityTypeFromId` then again we'd run into the same problem of keeping in sync two pieces of code that need to be updated anytime a new datatype is added

Alternatively, we could have a package-private / protected function that has the switch-case logic and can return JSON or IRI based on flag.

And then we have a public function wrapper around it, that just returns IRI

```Java
protected static String guessEntityTypeFromId(String id, boolean returnJsonEntity) {
    // switch-case logic here
}

public static String guessEntityTypeFromId(Stirng id) {
    return guessEntityTypeFromId(id, false);
}
```

This way we can get the IRI-JSON flag without ever exposing JSON serialization internals.

**Comment by Tpt** [comment]
It sounds like a great plan!

**Comment by snehasi** [comment]
Hi @Tpt,

I've opened PR #498 with these changes, could you please take a look?

Thank you!
