### ISSUE TITLE
Support of "new" data types

### ISSUE THREAD

**Issue by skodapetr** [Wikidata/Wikidata-Toolkit#430]
Are ```musical-notation``` and ```geo-shape``` supported?

I was able to found ```geo-shape``` as a value of ```JSON_DT_GEO_SHAPE``` but it seems to not be used anywhere. The ```musical-notation``` is not defined in that class.

As far as I understand those are datatypes, that are supported as "uknown" as a result of #422 - so they can be read, saved, but it seems to be that they can not be created.

Please correct me here if I'm mistaken:
* The new value is put into ```ValueSnakImpl```
*  ```ValueSnakImpl``` use ```getJsonPropertyTypeForValueType``` to determine the type unless the value is instance of ```TermImpl```
* This function decide based on a subclass of ```Value```

So in order to support ```geo-shape``` and ```musical-notation```  new subclasses of ```Value``` need to be created and make functions should be added to ```Datamodel``` as there is no way how to set the datatypes directly to the ```ValueSnakImpl```.

**Comment by wetneb** [comment]
Hi @skodapetr,

Yes both `musical-notation` and `geo-shape` values are supported, because the datavalues they use have type `string`, which is implemented.

It's a bit confusing but there is a distinction between the *datatype* of a property and the underlying *datavalue type*. Properties of datatype string, external-id, geoshape, mathematical formula, musical notation, Commons file (and probably others I am forgetting) all use a `string` datavalue, which is basically the only thing we care about in WDTK to edit items with claims using these datatypes. The `UnsupportedValue` class is only going to be used for datavalues of unknown types.

That being said it is true that we could add URIs and other JSON constants to represent the datatypes you mention explicitly in WDTK, but yes #422 should have made it unnecessary (if we got things right).

**Comment by skodapetr** [comment]
@wetneb I see, still could I ask you for a brief example of how to create those values.  
I would expect a method on the ```Datamodel`` but I can not find any method that contains for example ```music``` that could indicate that the returned value is of  ```musical-notation```` type.

Although from your explanation I should probably use ```Datamodel.makeStringValue``` and set the ```datatype``` later somewhere else - unfortunately I do not know how to do that.

**Comment by wetneb** [comment]
Yes, in practice you just need to pretend the property has `string` datatype. Just do everything as if you wanted to add a string claim - no need to set the datatype. The Wikibase API will accept this claim as such even if the property has `musical-notation` datatype.

**Comment by skodapetr** [comment]
You are right, thank you. We had some troubles updating those two types, that is why I thought it might be caused by Wikidata-Toolkit. But it seems we just provided an invalid value (so far tested only on ```geo-shape```).
