### ISSUE TITLE
Creation of QuantityValues: use ItemIdValue instead of String for unit

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#459]
We have introduced `getUnitItemId()` recently (551f3da06), solving a discrepancy with the rest of the interfaces: units are items, so they should be represented by `ItemIdValue`s instead of `String`s.

However, we have not adapted the Datamodel helper to create quantities using an `ItemIdValue` as unit. We should do that, and deprecate methods/constructions which rely on passing `String`s around.

**Comment by Tanish-Gupta** [comment]
Hi,
We were planning to work on this issue. Can you please confirm if the issue is still open? 

Thank you

**Comment by wetneb** [comment]
Yes it is! Thank you for offering to work on this!

**Comment by Tanish-Gupta** [comment]
That's great. 
Looking forward to work on it

**Comment by kanikasaini** [comment]
Hello, Tanish and I working on this as a team. 
I have changed the function as follows where we use ItemIdValue's getId() instead of String. 

<img width="831" alt="image" src="https://user-images.githubusercontent.com/20171105/82749686-87778b00-9dc8-11ea-8515-41e199a05221.png">

I have written the test case as well. Can you please confirm if that is how we want to test it out?

<img width="766" alt="image" src="https://user-images.githubusercontent.com/20171105/82749772-256b5580-9dc9-11ea-95f5-01aa194ff123.png">

Once approved, I will add the deprecated annotation, and appropriate javadoc comments and names for all functions and tests. 

Thank you for all the help and patience! :)

**Comment by wetneb** [comment]
That is great! I think we should also consider changing QuantityValueImpl to store the unit as an item directly, on the long term. But perhaps this is easier to do once the relevant methods/constructors have been deprecated for a long time.

**Comment by kanikasaini** [comment]
Thank you for the help. Should I send the PR to master branch?
Also, do we want to keep the tests for the deprecated functions? If yes, should the new tests be named like testGetQuantityValueItemIdValue() and testGetQuantityValueNoBoundsItemIdValue()?

<img width="592" alt="image" src="https://user-images.githubusercontent.com/20171105/82763227-b5d68400-9e23-11ea-8fc1-cd38b1857699.png">

Thank you.

**Comment by wetneb** [comment]
Sure, feel free to send a PR, we can discuss your changes there. You will get an opportunity to fix any problems in the PR, you do not need to get it right the first time.

**Comment by wetneb** [comment]
@darecoder1999 wonderful!
I would say #497 is a good first step but we should ideally store the unit as an ItemIdValue rather than as a string internally. Because of the conversion to a String, this is losing any extra data stored in the ItemIdValue.
In OpenRefine, this makes it impossible to use a cell reconciled to a new item as a unit.

**Comment by wetneb** [comment]
Closed by #593.
