### ISSUE TITLE
QueryLogs deanonymization 

### ISSUE THREAD

**Issue by MohamedRagabAnas** [Wikidata/Wikidata-Toolkit#538]
Hello,
Is there any script of class in the project that is doing deanonymization for the query logs, so the queries could be rerun again?

Thanks in advance for your help and support !

**Comment by mkroetzsch** [comment]
The anonymisation was there to protect confidential personal information. Having a script to undo this would defeat the purpose, wouldn't it? However, many queries are not affected in their meaning and can be run as before. Only strings and geographic coordinates had to be changed in ways that cannot be fully recovered. See the [Wikidata SPARQL query log page](https://iccl.inf.tu-dresden.de/web/Wissensbasierte_Systeme/WikidataSPARQL/en) for details on the anonymisation.

Of course, you should also take into account that Wikidata has changed since the logs were recorded, so queries may return different results if evaluated on the current data. Indeed, many queries are created by software tools that prepare changes of the data, so that it is likely that query results change soon after the query was issued (e.g., some tools use queries to find out if an item from an external data collection is already present in Wikidata, and import it if not).
