### ISSUE TITLE
Inviting robertvazan to the project

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#565]
I would like to invite @robertvazan to the project so he can review PRs.
His contributions in PRs and discussions in issues speak for themselves, I would say.

**Comment by Tpt** [comment]
It would be great indeed!
@lydiapintscher may you do that?

**Comment by wetneb** [comment]
I can take care of it I think - I just wanted your thumbs up before

**Comment by wetneb** [comment]
@Tpt I also made you an admin so you should be able to manage the project collaborators as well

**Comment by Tpt** [comment]
@wetneb Thank you!

**Comment by robertvazan** [comment]
How does this change the collaboration process? I guess discussion about planned changes remains the same, but how about actual commits? Does this mean developing in a branch instead of a fork and merging the branch myself without review? Or is there still review before branch merge?

What to do with the lexeme editing code? Most of it is already in my fork. I would like to complete it in the coming days. Should I make a pro-forma PR to avoid having to migrate the commits to a branch?

**Comment by wetneb** [comment]
In general I'd say it's good to always let someone else review your changes - but now you can also review and merge ours :)

You can develop in your fork or in a branch of the official repository as far as I am concerned (I use the official repository myself, but I feel slightly bad about it, I think it would be cleaner to use a fork).

**Comment by robertvazan** [comment]
I have accepted the invitation. I will continue using pull requests for larger changes since pull requests provide structure for the process. Push access will however make it easier to commit bugfixes and other small changes without the overhead of pull requests. This will save some time for all of us. Thanks.

**Comment by wetneb** [comment]
> Push access will however make it easier to commit bugfixes and other small changes without the overhead of pull requests.

I would still do PRs even for bug fixes actually :)

**Comment by robertvazan** [comment]
@wetneb I have never worked on shared project on GitHub before, so it's a bit confusing for me and I am guessing what the rules are. So sure, I will definitely send even bugfixes for review.
