### ISSUE TITLE
Support EDTF

### ISSUE THREAD

**Issue by Lhaaits** [Wikidata/Wikidata-Toolkit#700]
I noticed that org.wikidata.wdtk.datamodel.interfaces.DatatypeIdValue does not contain [EDTF](https://www.wikibase.consulting/wikibase-edtf/) (Extended Date Time Format) and I would like to add this.

**Comment by wetneb** [comment]
Since Wikibase lets extensions define new datatypes, we should make sure that it is not necessary to modify Wikidata-Toolkit itself to use those datatypes.

As far as I know, it should already be possible for you to use Wikidata-Toolkit to work with EDTF values on a Wikibase instance.
Notice that the list of datatypes stored in `DatatypeIdValue` is actually a list of static strings. That means that you can actually supply your own IRI for the EDTF datatype and instanciate a DatatypeIdValue with that (without making any change to Wikidata-Toolkit).

Also, retrieving values (via `wbgetentities`) and editing them (via `wbeditentity` or its friends) should already be supported because EDTF uses the `string` datavalue type, which is already supported.

That being said, if you want to contribute a canonical IRI for the EDTF datatype and store it as a static string in Wikidata-Toolkit, I think that is totally fine.

**Comment by Lhaaits** [comment]
Thanks for the quick reply. I didn't realize I could supply my own datatype IRI. It might still be good to add the canonical IRI "http://wikiba.se/ontology#Edtf" (according to https://github.com/Wikidata/triplify-json), but I'll leave the conversion and stuff out then.

**Comment by Lhaaits** [comment]
Aw no push permission..

**Comment by wetneb** [comment]
The way it works in GitHub is that you need to create a "pull request":
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by Lhaaits** [comment]
Done: https://github.com/Wikidata/Wikidata-Toolkit/pull/701
